# Copyright (c) Arduino s.r.l. and/or its affiliated companies
# SPDX-License-Identifier: Apache-2.0

CONFIG_FPU=y
CONFIG_USERSPACE=n
CONFIG_ARM_MPU=n

CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SPI=y
CONFIG_ADC=y
CONFIG_PWM=y

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

CONFIG_LLEXT_STORAGE_WRITABLE=n
CONFIG_LLEXT_HEAP_SIZE=16

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_ISR_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=512

CONFIG_BOOT_BANNER=y
CONFIG_THREAD_NAME=n
CONFIG_THREAD_STACK_INFO=n
CONFIG_THREAD_MONITOR=n
CONFIG_INIT_STACKS=n
CONFIG_STACK_CANARIES=n
CONFIG_STACK_SENTINEL=n
CONFIG_DYNAMIC_INTERRUPTS=n
